### ISSUE TITLE
Main page - Newsletter subscription colors to change

### ISSUE THREAD

**Issue by zsofimajor** [drupalironcamp/website#13]
Main page - Newsletter subscription - confirmation text and URL color should be changed. Currently it's pink, it should be white.

Note: this might be already fixed.

**Comment by petrillek** [comment]
It appears ok.

![image](https://cloud.githubusercontent.com/assets/5556405/16587915/1ab65a64-42cd-11e6-8d62-6031a8b52a18.png)
![image](https://cloud.githubusercontent.com/assets/5556405/16587922/22051076-42cd-11e6-9500-74bb5b092f4d.png)
