### ISSUE TITLE
Main page - News section - background for texts

### ISSUE THREAD

**Issue by zsofimajor** [drupalironcamp/website#14]
Currently there is no background visible for texts (or full opacity?), so the texts can't be read.
<img width="1277" alt="screen_shot_2015-06-29_at_19 16 01" src="https://cloud.githubusercontent.com/assets/4191750/15656346/70cbda20-26a6-11e6-8fe3-a7642de90fff.png">

Note: this might be already fixed.

**Comment by petrillek** [comment]
![image](https://cloud.githubusercontent.com/assets/5556405/16587763/7674041a-42cc-11e6-85fc-e942e5e6fe3b.png)

I've checked the styling. It was already fixed. I've only updated styling for slider dots… #25
