### ISSUE TITLE
Footer - mention Platform.sh there

### ISSUE THREAD

**Issue by zsofimajor** [drupalironcamp/website#15]
Please add a text in the footer (probably below the disclaimer/code of conduct links) to platform.sh (https://platform.sh).
The text should be: Hosting powered by Platform.sh
'Platform.sh' should link to their website

Also the logo should be added if possible: https://platform.sh/images/logo-white-2x.png

**Comment by ChandeepKhosa** [comment]
Let's do this in 2 stages

1) a very quick MVP of text
2) logo

**Comment by ChandeepKhosa** [comment]
@zsofimajor this is on the 'disclaimer/ page as text, is it ok there or is it also required on the footer of every page?

**Comment by ChandeepKhosa** [comment]
decision made by Zsofi : on all pages

**Comment by petrillek** [comment]
I've created the link + logo of platform.sh and put it in footer. @zsofimajor Please, check it to if its ok. 
I've also do few changes in the overall footer styling – removing the absolute positioning etc…

**Comment by miromichalicka** [comment]
<img width="598" alt="screen shot 2016-09-09 at 2 53 23 pm" src="https://cloud.githubusercontent.com/assets/1741875/18387492/3557ced0-769d-11e6-962f-f347a036dfbc.png">
