### ISSUE TITLE
Fix Twitter box in footer

### ISSUE THREAD

**Issue by mojzis** [drupalironcamp/website#3]
_From @zsofimajor on March 20, 2016 19:42_

It looks like Twitter changed something, therefore the twitter box doesn't look nice anymore. It should be fixed to match the designs.

_Copied from original issue: drupalironcamp/campsite-2015#107_

**Comment by mojzis** [comment]
_From @klukacin on April 5, 2016 19:25_

@zsofimajor I can't assign this one to me and do you have designs somewhere or should twitter just be in white box?

**Comment by mojzis** [comment]
_From @zsofimajor on April 5, 2016 19:29_

@klukacin all the designs are here: https://drive.google.com/open?id=0B78nd8vPZJK3QmxRbXRNb1ZXWlE

**Comment by klukacin** [comment]
Deployment procedure:
Pull code 
Configure

## Twitter module configuration
1. Go to http://yourdomain.com/admin/modules and enable: OAuth, OAuth Provider UI, Twitter, Twitter actions, Twitter Last Tweet Field, Twitter Post, Twitter Signin
2. Go to https://apps.twitter.com/app/new and create Twitter application (Name, Description and Website), under Callback URL input http://yourdomain.com/twitter/oauth
3. After creating Twitter application go to "Keys and Access Tokens" tab, copy Consumer Key (API Key) and Consumer Secret (API Secret) into the http://yourdomain.com/admin/config/services/twitter/settings and paste it
4. Go to http://yourdomain.com/admin/config/services/twitter and click on "Go to Twitter to add an authenticated account" button 
5. Authorize the app with your Twitter credentials
6. On http://yourdomain.com/admin/config/services/twitter check TWEETS checkbox and save changes
7. Go to http://yourdomain.com/admin/structure/block, click "delete" link on "Latest tweet embed", then drag & drop "Tweets" to Footer (or select Footer from select box), save
8. Go to http://yourdomain.com/admin/config/system/cron and configure cron 

You can see all tweets at http://yourdomain.com/tweets. If you don't see any Tweets coming up, remember to run cron on your Drupal site.

**Comment by miromichalicka** [comment]
<img width="625" alt="screen shot 2016-06-21 at 5 21 57 pm" src="https://cloud.githubusercontent.com/assets/1741875/16237607/7acea762-37dd-11e6-897f-df55e54c450a.png">
