### ISSUE TITLE
[CfP] - User should be able to submit session proposal

### ISSUE THREAD

**Issue by miromichalicka** [drupalironcamp/website#30]
As User
I want to submit session proposal
because I'm interested in presenting.

Given I'm authenticated user
When I click "Submit session" button
Then I can fill in and submit Session registration form.
- [x] Add Submit session button to homepage buttons next to Buy you ticket
- [x] Add permissions to authenticated user for creating Session content.
- [x] Hide text formats info.
- [x] Hide room and date fields
- [x] Disable preview
- [x] Fix theming
- [x] Speakers - "Add another item" button -> "Add another speaker" 
- [x] entity reference field are buggy: There are no entities matching <new enitity title> https://www.drupal.org/node/2080063

**Comment by radimklaska** [comment]
Free tagging entity reference to a vocabulary does not create the term, only allows existing terms - https://www.drupal.org/node/1472596

> Yes, that's by design. Entity Reference doesn't create entities.
> https://www.drupal.org/node/1472596#comment-5703784

There is a patch, but we have no data, let's just switch to term reference...

**Comment by radimklaska** [comment]
This was added:
- session submission form styles
- keyword field field changed to term reference

Everything was deployed to prod.
