### ISSUE TITLE
Update Mailchimp settings

### ISSUE THREAD

**Issue by radimklaska** [drupalironcamp/website#46]
When I tested "SIGN UP FOR UPDATES:" on new frontpage I got this message: 

> radim@klaska.net is already subscribed to list Drupal Iron Camp Newsletter 2015. Click here to update your profile.

2015 is wrong

**Comment by petrillek** [comment]
I think we should omit the year at all. It doesn't make too much sense to manage multiple lists per every year…

**Comment by petrillek** [comment]
I have removed the year from the list name and also checked all the forms and repaired them. So after confirming your email you will end up on a page with proper address (Venue in Prague instead of in Budapest) etc…

**Comment by petrillek** [comment]
Please, review and close. :)
