### ISSUE TITLE
Default user image lost

### ISSUE THREAD

**Issue by miromichalicka** [drupalironcamp/website#47]
<img width="978" alt="screen shot 2016-08-13 at 8 15 10 pm" src="https://cloud.githubusercontent.com/assets/1741875/17644840/c7cf43da-6192-11e6-840f-5e49a257591e.png">

**Comment by radimklaska** [comment]
fixed in 61b586a (I messed up the issue number in commit message)

http://www.drupalironcamp.com/community/attendees
