### ISSUE TITLE
Footer > Twitter block : text isn't readable, should be white

### ISSUE THREAD

**Issue by ChandeepKhosa** [drupalironcamp/website#49]
See http://screencast.com/t/KNnHlhUe6

**Comment by miromichalicka** [comment]
For me its working 
<img width="729" alt="screen shot 2016-08-16 at 4 21 05 am" src="https://cloud.githubusercontent.com/assets/1741875/17685975/e75211ec-6368-11e6-8380-219e9ff616ca.png">

**Comment by ChandeepKhosa** [comment]
It's working for me too today, strange both times were with Chrome

**Comment by ChandeepKhosa** [comment]
This keeps re-occurring from time to time. It might be with slower connections like my current one

**Comment by ChandeepKhosa** [comment]
The site seems to be loading a lot faster now and I haven't seen this re-occur in the past few days 👍
