### ISSUE TITLE
Clean up spam accounts on live site

### ISSUE THREAD

**Issue by mojzis** [drupalironcamp/website#5]
_From @radimklaska on March 17, 2016 13:29_

There is bunch of spam accounts on live site. We should clean this up and prevent new creation of new ones.
- maybe just a core setting since only users with valid ticket should have an account
- not all blocked account seem to be spam, see /user/200

_Copied from original issue: drupalironcamp/campsite-2015#105_

**Comment by mojzis** [comment]
_From @miromichalicka on March 20, 2016 18:52_

I wouldn't block registrations without valid ticket, because we want people to submit their session proposals. I often do that without ticket.

**Comment by miromichalicka** [comment]
On the call we agreed to delete all accounts except admin and editor accounts of the team.

**Comment by miromichalicka** [comment]
Deleted
