### ISSUE TITLE
Grant GitHub & CMS access to Chandeep

### ISSUE THREAD

**Issue by ChandeepKhosa** [drupalironcamp/website#51]
:)

**Comment by miromichalicka** [comment]
Invite for Github sent, I will give you access to cms after you will register there.

**Comment by ChandeepKhosa** [comment]
Great I have access to GitHub now

**Comment by ChandeepKhosa** [comment]
Just waiting on CMS access now @miromichalicka :)

**Comment by miromichalicka** [comment]
You are still not registered on website. We are working with personalised accounts.

**Comment by ChandeepKhosa** [comment]
Ah apologies, I thought you meant register on github, not on the website. Have registered on website now

**Comment by miromichalicka** [comment]
done
