### ISSUE TITLE
GitHub > Organisation : List more contributors

### ISSUE THREAD

**Issue by ChandeepKhosa** [drupalironcamp/website#52]
On https://github.com/orgs/drupalironcamp/people it currently only displays Istvan, Miro, Tompa. From looking at the list of contributors to the repo 'website', we should extend this to include
- rinasek
- radimklaska
- petrillek
- acervulus
- aboros
- mojzis
- klukacin
- bjaspan

I'm happy to add these once I get access to do so.

**Comment by miromichalicka** [comment]
This is personal setting of all people.
