### ISSUE TITLE
Review Google PageSpeed Insights suggestions

### ISSUE THREAD

**Issue by ChandeepKhosa** [drupalironcamp/website#54]
I noticed my computer loaded the site slowly and the fonts were messed up for a few seconds before they fixed themselves (in Budapest with a 6 Mbps connection). I thought I'd see what PageSpeed Insights said about it
- https://developers.google.com/speed/pagespeed/insights/?url=drupalironcamp.com&tab=desktop
- https://developers.google.com/speed/pagespeed/insights/?url=drupalironcamp.com&tab=mobile

**Comment by ChandeepKhosa** [comment]
I have turned on Drupal caching on the Live site. Previously it was like this http://screencast.com/t/oTvN9XbZk

We may benefit from setting this as hard setting in our settings.php file

**Comment by ChandeepKhosa** [comment]
I have now enabled 

CACHING
'Cache pages for anonymous users', 'Cache blocks', 

Minimum cache lifetime = 0, Expiration of cached pages = 15m

BANDWIDTH OPTIMIZATION
Compress cached pages = enabled
Aggregate and compress CSS files = enabled
Aggregate JavaScript files = enabled

This is how it looks after 
http://screencast.com/t/oFrmat9N

**Comment by petrillek** [comment]
Hey Chandeep, 
thanks, but if you are going to make changes like this, its always a good idea mention them on Slack. I will be cautious, that if the settings was like that, it might have some reason. And Radim or Miro knows about it. I'm not saying it wasn't like that by mistake. :)

**Comment by ChandeepKhosa** [comment]
Sure thing, I usually would have, must have been too excited.
Won’t happen again :)

**Comment by petrillek** [comment]
Yeah, excited, that is the word. :) All good.

**Comment by miromichalicka** [comment]
This probably wont be relevant with Belgrade theme.
