### ISSUE TITLE
Update dates of attendance in user profile 

### ISSUE THREAD

**Issue by mojzis** [drupalironcamp/website#6]
_From @miromichalicka on March 17, 2016 13:28_

Currently, we have in user profile Monday-Friday as conference days, we need to update this to Thursday-Sunday.
<img width="305" alt="screen shot 2016-03-17 at 2 12 59 pm" src="https://cloud.githubusercontent.com/assets/1741875/13847259/92d4dd22-ec4c-11e5-9e7b-c6a9055b0164.png">

_Copied from original issue: drupalironcamp/campsite-2015#104_

**Comment by miromichalicka** [comment]
Delete all blocked accounts and make sure that no account has data in this field before reverting features.
