### ISSUE TITLE
Attendee list needs 1 more result to fill grid

### ISSUE THREAD

**Issue by ChandeepKhosa** [drupalironcamp/website#69]
on attendee list, the 1st page has an empty slot in the bottom right http://screencast.com/t/R9L9CqF6igKD with MacBook Pro 15” standard resolution & Chrome (latest)

suggested fix : modify view "User list : Attendee list" and increase number of results from 15 to 16

**Comment by petrillek** [comment]
This issue is solved in pull request #67 … Which is waiting for merge…
