### ISSUE TITLE
Add integration with ticket selling platform

### ISSUE THREAD

**Issue by mojzis** [drupalironcamp/website#7]
_From @miromichalicka on June 9, 2015 14:59_

If we are going to sell tickets via eventbrite, use https://www.drupal.org/project/eventbrite_api or https://www.drupal.org/project/eventbrite to create user account on site after ticket is purchased.

_Copied from original issue: drupalironcamp/campsite-2015#75_

**Comment by mojzis** [comment]
_From @rinasek on June 9, 2015 15:12_

We need to check what will we use for ticket sales.

**Comment by mojzis** [comment]
_From @miromichalicka on March 20, 2016 18:41_

neither of modules mentioned before is working because eventbrite deprecated their apis some time last year

**Comment by miromichalicka** [comment]
We have basic integration ready, so account is created for user after ordering ticket. We need go further and map Name and Surname fields.

**Comment by radimklaska** [comment]
Done! :-)

**Comment by radimklaska** [comment]
Reopening, we need to sync more data:
- field_user_job_speeding_date
- field_user_size_t_shirt
- field_user_participate_days
- field_user_dietary_needs

**Comment by miromichalicka** [comment]
We agreed that  it is enough to have these data in eventbrite

**Comment by miromichalicka** [comment]
These fields should be deleted.

**Comment by radimklaska** [comment]
aha, these fields came back as export from old DB on Peter's local. We were not sure, so we picked the safe way of keeping them in. Now we that we are sure, we can remove these... Thanks for reminder! :-)
