### ISSUE TITLE
Fix redirects

### ISSUE THREAD

**Issue by radimklaska** [drupalironcamp/website#73]
Current situation:
- drupalironcamp.com redirests to www.drupalironcamp.comv
- www.drupalironcamp.com loads OK
- www.drupalironcamp.com/about loads OK
- drupalironcamp.com/about Error 521

I think the desired state is to have everything working on www. version and redirect the rest.

I tried to set this up, but results were cached by CloudFlare which I didn't realized at the beginning.

**Comment by miromichalicka** [comment]
seems to be working now, missing images is another issue
