### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by miromichalicka** [drupalironcamp/website#74]
I should be able to see whole image scaled down to 220x220

**Comment by zsofimajor** [comment]
The default ratio for the logos should be rectangle, not square actually.

**Comment by calin-marian** [comment]
@zsofimajor I don't think we should touch the aspect ratio, just scale them to fit, keep the original aspect ration, and center them.
I attached a screenshot with my idea, using some logos I had on my laptop. I highlighted the images to be able to see what's going on.
<img width="1175" alt="sponsors___site-install" src="https://cloud.githubusercontent.com/assets/4013741/18520918/9321c750-7ab2-11e6-8489-6c01c995f396.png">

Btw, I'm working on this, but I don't have the rights to assign it to me.

**Comment by zsofimajor** [comment]
My main problem is that the Gold and Diamond logos are not bigger than the Silver, Bronze, etc. It would be nice to make them stand out somehow.

**Comment by petrillek** [comment]
@calin-marian We don't want to touch the aspect ratio of the logos itself. But the image style used on the site is Square. Zsofi want it to be more rectangle… And we will probably needs few more sizes to accommodate for different sponzors level.

**Comment by calin-marian** [comment]
How about this?
Diamond 50% width (2 per line)
Gold 33% width (3 per line)
Silver, Bronze 25% width (4 per line)
